### ISSUE TITLE
Intl not defined on LG G3 Stock Android browser

### ISSUE THREAD

**Issue by bonimba** [andyearnshaw/Intl.js#175] opened 2016-05-13 16:17 UTC
Hi all,
I have seen that a similar issue has been fixed for Samsung Stock browsers recently.

I still having this issue on this user agent: 
Mozilla/5.0 (Linux; U; Android 5.0; en-gb; LG-D855/V21a Build/LRX21R.A1446038723) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/34.0.1847.118 Mobile Safari/537.36. 

I will try to test in on several other phones

**Comment by caridy** [comment] 2016-05-13 16:30
dupe of https://github.com/andyearnshaw/Intl.js/issues/170

**Closed by caridy** 2016-05-13 16:30 UTC
