### ISSUE TITLE
Not working with certain iOS user-agent

### ISSUE THREAD

**Issue by unboundmusic** [andyearnshaw/Intl.js#161] opened 2016-04-02 05:05 UTC
Reproduce:

Set Safari user agent to:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13C75
```

And the polyfill does not load correctly.

**Comment by caridy** [comment] 2016-04-05 16:39
@unboundmusic we need more information here. how are you loading the polyfill, including the version? How are you testing that the polyfill is not loaded? Repro case maybe?

**Comment by caridy** [comment] 2016-05-12 17:15
dupe of https://github.com/andyearnshaw/Intl.js/issues/170

**Closed by caridy** 2016-05-12 17:15 UTC
