### ISSUE TITLE
Support "2-digit" month format

### ISSUE THREAD

**Issue by alexnb** [andyearnshaw/Intl.js#195] opened 2016-06-29 15:21 UTC
Hello,

unfortunately I cannot confirm that Issue #128 is resolved. I use Intl.js-1.2.4 with phantomjs-2.1.1 and still, the "2-digit month" option produces single-digit month values. The following QUnit test fails (actual result is "6"):

 assert.equal(new Intl.DateTimeFormat('en', {
        month: '2-digit'
   }).format(Date.now()), "06");

Could you please help, I guess this feature is quite commonly used (at least I need it urgendly :) ).

Thanks and best regards
Alexander

**Comment by caridy** [comment] 2016-07-01 03:51
few folks have been looking to add support for a single token formats, If nobody gets a PR before next Thru., I will attempt to implement it.

**Comment by caridy** [comment] 2016-07-01 15:59
dupe of https://github.com/andyearnshaw/Intl.js/issues/190

**Closed by caridy** 2016-07-01 15:59 UTC
