### ISSUE TITLE
'2-digit' day is formatted in the wrong way, if month is formatted to

### ISSUE THREAD

**Issue by donaldpipowitch** [andyearnshaw/Intl.js#275] opened 2017-04-25 11:28 UTC
**Code**

```js
var day1 = new Intl.DateTimeFormat('de-DE', {
  month: 'short',
  day: '2-digit'
}).formatToParts(new Date('2017-04-01T10:36:24Z'))[0].value;

var day2 = new Intl.DateTimeFormat('de-DE', {
  day: '2-digit'
}).formatToParts(new Date('2017-04-01T10:36:24Z'))[0].value;
```

**Expected behaviour**

```js
// in Chrome without polyfill
day1 === '01';
day2 === '01';
```

**Actual behaviour**

```js
// in IE10 with polyfill
day1 === '1'; // wrong 
day2 === '01';
```

**Comment by morhook** [comment] 2017-04-27 18:40
This same problem is happening to me on PhantomJS as part of my `Ember` build (runs test on chrome and PhantomJS by default).

**Comment by morhook** [comment] 2017-04-27 18:41
This one looks duplicate of https://github.com/andyearnshaw/Intl.js/issues/246 on a second read.

**Comment by donaldpipowitch** [comment] 2017-04-27 19:18
Yeah, seems to be a duplicate.

**Closed** 2017-04-27 19:18 UTC
