### ISSUE TITLE
Removing `locale-data/json/*.json` is a breaking change (v1.2.5)

### ISSUE THREAD

**Issue by tthew** [andyearnshaw/Intl.js#238] opened 2016-10-11 14:32 UTC
The last patch update (v1.2.5) introduces a breaking change by removing `locale-data/json/*json`.

**Comment by caridy** [comment] 2016-10-11 14:37
dupe of https://github.com/andyearnshaw/Intl.js/issues/227

**Closed by caridy** 2016-10-11 14:37 UTC

**Comment by tthew** [comment] 2016-10-11 14:42
This was rather more a reference to the fact that a breaking change was introduced in a patch update, an `npm install` will cause implementations to break unexpectedly.

**Comment by caridy** [comment] 2016-10-11 14:55
@tthew we were not expecting so many people importing from that folder, just like we didn't expect people importing from our `tests/` folder and few others which were also part of the npm and are now ignored for the sake of reducing the size of the tarball (it was ~100MB). We never document it, we never talk about it, it was just the source of the jsonp files. We understand that this might be an inconvenience, and probably we should have been more careful, but at least you have a path forward, just use the jsonp files as documented in the readme. We will be more careful next time.

**Comment by tthew** [comment] 2016-10-11 15:09
Sure. I concede that the json files were undocumented, so I guess it was a risky move to use them in the first place.

Like you say, the fix is simple, just import the jsonp instead (as expressed in the documentation!).

Thanks to all the contributors for all the hard work.
