### ISSUE TITLE
Bug with Chinese date

### ISSUE THREAD

**Issue by alex-seville** [andyearnshaw/Intl.js#88] opened 2015-03-27 17:28 UTC
With Intl:
(new Intl.DateTimeFormat('zh-Hant-HK', { year: 'numeric', month: 'long', day: 'numeric'})).format(new Date())

produces: 
"2015 年 3 月 27 日"

With Intl.js, it produces:
"2015 年 三月 月 27"

**Comment by caridy** [comment] 2015-03-27 18:56
This should be fixed by PR #85:

```
node
> require('./')
{}
> (new IntlPolyfill.DateTimeFormat('zh-Hant-HK', { year: 'numeric', month: 'long', day: 'numeric'})).format(new Date())
'2015年3月月27日'
```

If you're in a hurry, ping me (you know where to find me). If flickr is using the internal polyfill service, this will be coming to you today :)

**Comment by caridy** [comment] 2015-03-27 18:56
I will keep this open for now, until we merge that release the new version.

**Comment by okuryu** [comment] 2015-03-28 00:06
This is a duplicate of #69.

**Closed** 2015-03-31 04:18 UTC
