### ISSUE TITLE
Any tips on how to use with rollup for es2015 tree-shaking?

### ISSUE THREAD

**Issue by RoxKilly** [andyearnshaw/Intl.js#237] opened 2016-10-08 23:51 UTC
My `Angular 2` app coded in `typescript 2` uses this polyfill.  I have set `module:"es2015"` in `tsconfig.json` to allow for tree-shaking using Rollup.js [as recommended by Angular](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#tree-shaking)

When I run the app in the browser, I get the error
> global is not defined

I have tried using `rollup-plugin-commonjs` to convert the library to `es2015`

**rollup.config.js**
```
plugins: [
        nodeResolve({jsnext: true, module: true}),
        commonjs({
            include: 'node_modules/intl/**/*',
        })
]
```
When I run the app in the browser, I get the error:
> IntlPolyfill is not defined

On a line like:
> IntlPolyfill.__addLocaleData({locale:"en-US",...});

[I noticed here](https://github.com/andyearnshaw/Intl.js/blob/68514268e4f6b97a9323f6be9e75bd5a1216777a/CONTRIBUTING.md#source-code) that the library is written in `es6` so it should be compatible with `rollup`.  Any tips on how to use this library as `es6` modules?

**Comment by caridy** [comment] 2016-10-10 16:12
We intentionally don't expose the ES6 source to be used via rollup because this is a polyfill, and bundling polyfills with the rest of your app is not what we recommend.

As for the actually issue described here, this is a dupe of https://github.com/andyearnshaw/Intl.js/issues/218, for which we don't have a fix yet, but a workaround is possible.

**Closed by caridy** 2016-10-10 16:12 UTC
