### ISSUE TITLE
React Native 0.42 "TransformError"

### ISSUE THREAD

**Issue by jayesbe** [andyearnshaw/Intl.js#268] opened 2017-03-08 22:22 UTC
Just tried to use this lib on React Native. The app so far is fairly HelloWorld ish.

these are the exact steps I used.

npm install --save intl
npm install --save intl-locales-supported

I then added the following two lines to the top of my app.js

import 'intl';
import 'intl/locale-data/jsonp/en.js';

Thats it. Did not try to use intl in any way, no number formating, nothing.

Got 

Bundling `index.android.js`
  Transforming modules  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░  97.5% (721/740)...(node:45716) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1332): SyntaxError: TransformError: C:\src\project
Bundling `index.android.js`

**Comment by h0ward** [comment] 2017-03-09 02:58
try `mv node_modules/intl/.babelrc node_modules/intl/~.babelrc`, it works for me.

https://github.com/andyearnshaw/Intl.js/pull/264#issuecomment-279947557

**Comment by caridy** [comment] 2017-03-30 15:22
dupe of https://github.com/andyearnshaw/Intl.js/pull/264, fixed.

**Closed by caridy** 2017-03-30 15:22 UTC
