### ISSUE TITLE
IntlPolyfill.__localeSensitiveProtos.Date.toLocaleString doesn't work as specified

### ISSUE THREAD

**Issue by headcr4sh** [andyearnshaw/Intl.js#192] opened 2016-06-27 10:17 UTC
I have just tried v1.2.4 (latest) of the Intl polyfill.

According to #117 this issue should have been fixed by PR #146 .
Unfortunately, my latest tests indicate, that the opposite is still the case...

```javascript
(function () {
  var date = new Date(2016, 0, 1); // January, 1st 2016
  var locale = "en-us"; // Other locales won't work as well, btw.
  var format = { month: "long" }; // Valid date format according to the Intl spec.
  // Use the IntlPolyfill version of Date.toLocaleString even if the environment won't
  // actually need the polyfill 
  var str = IntlPolyfill.__localeSensitiveProtos.Date.toLocaleString.bind(date)(locale, format);
  if (str !== "January") {
    throw new Error("Intl polyfill is still defunct. Expected: 'January', got: '" +  str + "'!");
  }
})();
```

The result when executing the code abote is `Jan`. And that is clearly not the expected result when using the formatter `{ month: "long" }`.

I can confirm that the code above yields the correct result, when using v1.1.0 of the Intl polyfill.
So I assume a regression bug.

**Comment by caridy** [comment] 2016-07-01 16:00
dupe of https://github.com/andyearnshaw/Intl.js/issues/190

**Closed by caridy** 2016-07-01 16:00 UTC

**Comment by headcr4sh** [comment] 2016-07-02 10:10
@caridy Sorrt... didn't see the duplicate. My bad...
